baseurl = "https://docs.spirx.io/"
languageCode = "en-us"
title = "SpirX Docs"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	author = "Adrian J. Collado"
	description = "Documentation for the SpirX game engine."
	copyright = "Released under the MIT license"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/SpirX/SpirX"

	version = "1.0.0"
	logo = "images/logo.png"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "red"
    	accent  = "teal"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"


[social]
	twitter = ""
	github  = "adriancollado"
	email   = "acollado@polaritech.com"


[[menu.main]]
	name   = "SpirX Docs"
	url    = "/"
	weight = 0

[[menu.main]]
	name   = "Beginner's Guide"
	url    = "guide/"
	weight = 20

[[menu.main]]
	name   = "Loader"
	url    = "loader/"
	weight = 30

[[menu.main]]
	name   = "Window"
	url    = "window/"
	weight = 40


[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
